# Generated by Django 4.2.17 on 2024-12-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_unix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='otp',
            field=models.IntegerField(default=False),
        ),
    ]
