# Generated by Django 4.2.17 on 2024-12-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_unix_app', '0002_userdata_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='otp',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
