# Generated by Django 4.2.17 on 2024-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_unix_app', '0003_alter_userdata_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='otp',
            field=models.IntegerField(default=False),
        ),
    ]
