# Generated by Django 4.2.17 on 2024-12-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_unix_app', '0004_alter_userdata_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
